### PR TITLE
64 view booking list should show parking choice

### LINKED ISSUE #64: View booking list should show parking choice
Same should apply to the previous bookings

### PR DESCRIPTION
**Pull request by AtifKhokhar**
fixes #64 . 
image

### CODE REVIEW

**Comment by danielrbradley** [comment]
One question to discuss ... how to we adapt this for offices which aren't using this app to manage their car parking? I.e. saying "without parking" might be misleading or confusing given that they can park regardless of what the app says.

**Comment by AtifKhokhar** [comment]
> One question to discuss ... how to we adapt this for offices which aren't using this app to manage their car parking? I.e. saying "without parking" might be misleading or confusing given that they can park regardless of what the app says.

@chapmanio @Jumee-LDN any suggestions as to how to tackle this in a UX/UI perspective?

**Comment by chapmanio** [comment]
@AtifKhokhar I'd just label it like this:

- 24th July at The Office (+ Parking)
- 17th July at The Office

**Comment by AtifKhokhar** [comment]
> @AtifKhokhar I'd just label it like this:
> 
> * 24th July at The Office (+ Parking)
> * 17th July at The Office

cheers many thanks

**Pull request merged**
