### PR TITLE
implemented banner for IE users encouraging them to use modern browsers.

### PR DESCRIPTION
**Pull request by AtifKhokhar**
image

### CODE REVIEW

**Comment by danielrbradley** [comment]
Think we could polish up the alignment. Also, does this work well on responsive layouts?

**Comment by AtifKhokhar** [comment]
> Think we could polish up the alignment. Also, does this work well on responsive layouts?

should responsive really matter given that IE would be used on a desktop and not a mobile device?

**Review by danielrbradley — APPROVED** [review]
Cool, alignment looks good. Assuming @Jumee-LDN  is all happy too then you're good to merge.

**Comment by Jumee-LDN** [comment]
Looks good to me!

**Pull request merged**
