### PR TITLE
42 styling review

### PR DESCRIPTION
**Pull request by chapmanio**
Partially completes https://github.com/o2Labs/office-booker/issues/42

Generally styling and structure updates for the **Admin** pages.  Includes renaming several components and updated the file structure.

Significant re-write of **New Booking** page to display and cope with quotes.  Now also responds if a parking quota is available for the selected location or not.

Also updated the bookings listing page, again to reflect if a parking quota is available, and styling updates.

The **users** area only has top-level styling updates, and still requires the review that has gone into the above pages.  This will happen and be added as a separate PR asap.

I will then do a general run-through of styling and structure for the main app and again will submit a separate PR for any changes.

### CODE REVIEW

**Comment by chapmanio** [comment]
I will investigate the double-loading of the bookings, I assume this is due to an effect trigger.  Hopefully it will be simple to resolve!

The native date-picker isn't cross browser and platform compatible, hence changing to the material picker.  There is a keyboard picker, which is their preferred implementation, but I was hesitant to use this due to the validation considerations (as we have a fixed date-range that should be selected, this is overridden by manually entered dates.

https://material-ui-pickers.dev/demo/datepicker

I will investigate how simple it would be to implement to keyboard picker without introducing significant validation code.

Regarding the parking selection, it is bad practice to have radio buttons without a default selection.  If a default/null selection is required then a select list is the correct method, although for a simple yes/no selection this would cause unnecessary extra interactions for the user.

If there are only two options then either a radio button with a default selection, or a checkbox are the best implementations.  The question we are asking is "do you require access to the office, OR do you require access to the office **and** parking".  Considering parking is an _addition_ to the main form selection, a checkbox (or toggle selection) is the correct implementation.

**Comment by danielrbradley** [comment]
Yup, makes sense with the date picker - as I say - the one you've got there works fine for our scenario.

Another option for the parking option in the admin ... could we just re-use the multi-select button from the main booking screen?

**Comment by chapmanio** [comment]
The multiple calls to the API have been fixed on both admin and home.

I'm going to delay the keyboard date picker for now as it is causing issues with date-fns, it will need digging into deeper.  I'm also happy to continue the debate around the parking selection, but I still believe a checkbox/radio button with default/toggle button is the best option.

For now, the improvements from this PR are worth getting merged (mainly for the dynamic hiding of parking options) ASAP considering go-live.

**Comment by chapmanio** [comment]
I have been incorrectly referring to "toggle buttons", where I actually meant "switches":

https://material-ui.com/components/switches/

**Pull request merged**
